framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    group: symfonicat
                    consumer: '%env(MESSENGER_CONSUMER_NAME)%'
                    redeliver_timeout: 3600
                    claim_interval: 60000
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000

            failed:
                dsn: '%env(MESSENGER_FAILED_TRANSPORT_DSN)%'
                options:
                    group: symfonicat_failed
                    consumer: '%env(MESSENGER_CONSUMER_NAME)%'

            sync: 'sync://'

        routing:
            Symfony\Component\Mercure\Update: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
