security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        symfonicat_core_provider:
            id: Symfonicat\Security\AdminUserProvider

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        core:
            pattern: ^/core
            provider: symfonicat_core_provider
            form_login:
                login_path: symfonicat_core_login
                check_path: symfonicat_core_login_check
                default_target_path: symfonicat_core_login
                always_use_default_target_path: true
                username_parameter: email
                password_parameter: password
                enable_csrf: true
                csrf_token_id: symfonicat_core_login
            login_throttling:
                max_attempts: 10
                interval: '5 minutes'
                lock_factory: lock.factory
                cache_pool: cache.rate_limiter
            logout:
                path: /core/logout/clear
                target: symfonicat_subdomain_root
        main:
            lazy: true

    access_control:
        - { path: ^/core/login/check, roles: PUBLIC_ACCESS }
        - { path: ^/core/login, roles: PUBLIC_ACCESS }
        - { path: ^/core/logout, roles: PUBLIC_ACCESS }
        - { path: ^/core/logout/clear, roles: PUBLIC_ACCESS }
        - { path: ^/core, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
