symfonicat:
    vendors:
        - symfonicat
    admin:
        symfonicat_parcel:
            -
                id: core/domainparcel
                path: assets/parcel/domainparcel
                vendor: core
            -
                id: core/endpointparcel
                path: assets/parcel/endpointparcel
                vendor: core
            -
                id: core/subdomainparcel
                path: assets/parcel/subdomainparcel
                vendor: core
        symfonicat_domain: []
        symfonicat_endpoint: []
        symfonicat_subdomain: []
        symfonicat_application: []
        symfonicat_env_parent: []
        symfonicat_env: []
        symfonicat_application_env: []
        symfonicat_domain_env: []
        symfonicat_middleware:
            -
                id: 1
                class: Symfonicat\Middleware\DomainMiddleware
            -
                id: 2
                class: Symfonicat\Middleware\EndpointMiddleware
            -
                id: 3
                class: Symfonicat\Middleware\SubdomainMiddleware
            -
                id: 4
                class: Symfonicat\Middleware\TestMiddleware
        symfonicat_domain_middleware: []
        symfonicat_domain_subdomain: []
        symfonicat_endpoint_env: []
        symfonicat_endpoint_middleware: []
        symfonicat_module:
            -
                id: symfonicat/analytics/main
                package: analytics
                vendor: symfonicat
        symfonicat_module_domain: []
        symfonicat_module_endpoint: []
        symfonicat_module_subdomain: []
        symfonicat_parcel_env: []
        symfonicat_subdomain_env: []
        symfonicat_subdomain_middleware: []
