symfonicat:
    vendors:
        - symfonicat
    admin:
        symfonicat_env_parent:
            -
                id: colors
        symfonicat_env:
            -
                id: primary
                env_parent_id: colors
        symfonicat_bundle: []
        symfonicat_domain:
            -
                id: example.com
                bundle_id: null
            -
                id: localhost
                bundle_id: null
        symfonicat_domain_env:
            -
                id: 1
                value: blue
                domain_id: localhost
                env_id: primary
            -
                id: 2
                value: blue
                domain_id: example.com
                env_id: primary
        symfonicat_subdomain:
            -
                id: core/subdomain1
                vendor: core
                bundle_id: null
        symfonicat_domain_subdomain:
            -
                domain_id: example.com
                subdomain_id: core/subdomain1
        symfonicat_application:
            -
                id: example-test
                name: 'Example Test'
                type: domain
                domain_id: example.com
                subdomain_id: null
                bundle_id: null
        symfonicat_application_env:
            -
                id: 1
                value: yellow
                application_id: example-test
                env_id: primary
        symfonicat_bundle_env: []
        symfonicat_module:
            -
                id: symfonicat/analytics/main
                package: analytics
                vendor: symfonicat
        symfonicat_module_domain:
            -
                module_id: symfonicat/analytics/main
                domain_id: example.com
            -
                module_id: symfonicat/analytics/main
                domain_id: localhost
        symfonicat_module_subdomain:
            -
                module_id: symfonicat/analytics/main
                subdomain_id: core/subdomain1
        symfonicat_subdomain_env:
            -
                id: 1
                value: green
                subdomain_id: core/subdomain1
                env_id: primary
