symfonicat_public_controllers:
    resource: ../../admin/src/Controller/
    type: attribute
    exclude:
        - ../../admin/src/Controller/Admin/

symfonicat_app_controllers:
    resource: ../../src/Controller/
    type: attribute
