<?php

namespace Symfonicat\Command;

use Symfonicat\Entity\Application;
use Symfonicat\Entity\Domain;
use Symfonicat\Entity\Endpoint;
use Symfonicat\Entity\Subdomain;
use Symfonicat\Repository\ApplicationRepository;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Twig\Environment;

#[AsCommand(
    name: 'symfonicat:application:build',
    aliases: ['symfonicat:electron:build'],
    description: 'Generate Electron application skeletons into application/<application.id>/.',
)]
final class ApplicationBuildCommand extends Command
{
    public function __construct(
        private readonly ApplicationRepository $applicationRepository,
        private readonly Environment $twig,
        #[Autowire('%kernel.project_dir%')]
        private readonly string $projectDir,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $applications = [];

        try {
            $applications = $this->applicationRepository->findAllOrdered();
            $this->clearOutputRoots();

            foreach ($applications as $application) {
                $this->buildApplication($application, $io);
            }
        } catch (\Throwable $exception) {
            $io->error($exception->getMessage());

            return Command::FAILURE;
        }

        $io->success(sprintf(
            'Generated %d application skeleton%s in application/.',
            count($applications),
            count($applications) === 1 ? '' : 's',
        ));

        return Command::SUCCESS;
    }

    private function buildApplication(Application $application, SymfonyStyle $io): void
    {
        $applicationId = trim((string) $application->getId());
        if ($applicationId === '') {
            throw new \RuntimeException('Application id cannot be empty.');
        }

        $outputDir = $this->applicationOutputDirectory($applicationId);
        $this->removePath($outputDir);
        $this->ensureDirectory($outputDir);

        file_put_contents($outputDir.'/main.js', $this->renderMainJs($application));
        file_put_contents($outputDir.'/package.json', $this->renderPackageJson($application));
        file_put_contents($outputDir.'/README.md', $this->renderReadme($application));

        $io->writeln(sprintf('<info>Generated application skeleton</info> %s', $applicationId));
    }

    private function renderMainJs(Application $application): string
    {
        $applicationId = trim((string) $application->getId());
        $template = $this->resolveTemplate($applicationId);

        return $this->twig->render($template, [
            'application' => $application,
            'application_config' => [
                'id' => $applicationId,
                'name' => $application->getName(),
                'targetId' => $application->getTargetId(),
            ],
            'start_url' => $this->startUrlFor($application),
        ]);
    }

    private function renderPackageJson(Application $application): string
    {
        $applicationId = trim((string) $application->getId());
        $productName = trim((string) $application->getName()) ?: $applicationId;
        $packageJson = [
            'name' => $this->sanitizePackageName($applicationId),
            'version' => '1.0.0',
            'private' => true,
            'main' => 'main.js',
            'scripts' => [
                'start' => 'electron .',
                'build' => 'electron-builder',
            ],
            'dependencies' => [
                'electron' => $this->rootPackageVersion('electron'),
            ],
            'devDependencies' => [
                'electron-builder' => $this->rootPackageVersion('electron-builder'),
            ],
            'build' => [
                'appId' => $this->sanitizeAppId($application),
                'productName' => $productName,
                'directories' => [
                    'output' => 'dist',
                ],
                'files' => [
                    '**/*',
                ],
            ],
        ];

        return json_encode($packageJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)."\n";
    }

    private function renderReadme(Application $application): string
    {
        $applicationId = trim((string) $application->getId());
        $productName = trim((string) $application->getName()) ?: $applicationId;

        return <<<MD
# {$productName}

Generated by `symfonicat:application:build`.

## Build

```bash
npm install
npm run build
```

The application start URL is baked into `main.js`.
MD;
    }

    private function resolveTemplate(string $applicationId): string
    {
        $override = sprintf('application/overrides/%s.js.twig', $applicationId);
        if ($this->twig->getLoader()->exists($override)) {
            return $override;
        }

        return 'application/main.js.twig';
    }

    private function startUrlFor(Application $application): string
    {
        $domain = $application->getDomain();
        if (!$domain instanceof Domain) {
            throw new \RuntimeException(sprintf('Application "%s" requires a domain.', $application->getId()));
        }

        $host = trim((string) $domain->getId(false));
        if ($host === '') {
            throw new \RuntimeException(sprintf('Application "%s" requires a valid domain.', $application->getId()));
        }

        $subdomain = $application->getSubdomain();
        if ($subdomain instanceof Subdomain) {
            $subdomainId = trim((string) $subdomain->getId(false));
            if ($subdomainId !== '') {
                $host = sprintf('%s.%s', $subdomainId, $host);
            }
        }

        $path = '';
        $endpoint = $application->getEndpoint();
        if ($endpoint instanceof Endpoint) {
            $path = $endpoint->getArgumentsPath();
        }

        return sprintf(
            'https://%s%s?%s',
            $host,
            $path,
            http_build_query(['application' => $application->getId()]),
        );
    }

    private function applicationOutputDirectory(string $applicationId): string
    {
        return rtrim($this->projectDir, '/').'/application/'.$applicationId;
    }

    private function clearOutputRoots(): void
    {
        $this->clearDirectory(rtrim($this->projectDir, '/').'/application', true);
        $this->clearDirectory(rtrim($this->projectDir, '/').'/electron', false);
    }

    private function clearDirectory(string $directory, bool $keepGitkeep): void
    {
        if (!is_dir($directory)) {
            return;
        }

        foreach (array_values(array_diff(scandir($directory) ?: [], ['.', '..'])) as $entry) {
            if ($keepGitkeep && in_array($entry, ['.gitkeep', '.gitignore'], true)) {
                continue;
            }

            $this->removePath($directory.'/'.$entry);
        }
    }

    private function ensureDirectory(string $directory): void
    {
        if (!is_dir($directory) && !mkdir($directory, 0755, true) && !is_dir($directory)) {
            throw new \RuntimeException(sprintf('Unable to create directory "%s".', $directory));
        }
    }

    private function removePath(string $path): void
    {
        if (is_link($path) || is_file($path)) {
            @unlink($path);

            return;
        }

        if (!is_dir($path)) {
            return;
        }

        foreach (array_values(array_diff(scandir($path) ?: [], ['.', '..'])) as $entry) {
            $this->removePath($path.'/'.$entry);
        }

        @rmdir($path);
    }

    private function sanitizePackageName(string $applicationId): string
    {
        $packageName = preg_replace('~[^a-z0-9._-]+~i', '-', $applicationId) ?: 'application';

        return trim($packageName, '-._') ?: 'application';
    }

    private function sanitizeAppId(Application $application): string
    {
        $id = trim((string) $application->getId());
        $id = preg_replace('~[^a-z0-9.]+~i', '.', $id) ?: 'application';

        return 'symfonicat.'.trim($id, '.');
    }

    private function rootPackageVersion(string $packageName): string
    {
        $packageJson = json_decode(file_get_contents($this->projectDir.'/package.json') ?: '', true);
        if (!is_array($packageJson)) {
            throw new \RuntimeException('Unable to read root package.json.');
        }

        foreach (['devDependencies', 'dependencies'] as $section) {
            $version = trim((string) ($packageJson[$section][$packageName] ?? ''));
            if ($version !== '') {
                return $version;
            }
        }

        throw new \RuntimeException(sprintf('Unable to determine "%s" version from root package.json.', $packageName));
    }
}
