parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Symfonicat\:
        resource: '../admin/src/'
        exclude:
            - '../admin/src/Composer/'
            - '../admin/src/DependencyInjection/'
            - '../admin/src/Entity/'
            - '../admin/src/Maker/'
            - '../admin/src/SymfonicatBundle.php'

    Symfonicat\Service\DomainService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Symfonicat\Service\PackageDiscoveryService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $vendors: '%symfonicat.vendors%'

    Symfonicat\Service\ApplicationService:
        arguments:
            $appSecret: '%kernel.secret%'
            $frameworkRouter: '@Symfonicat\Routing\ApplicationRouter.inner'

    Symfonicat\Routing\ApplicationRouter:
        decorates: 'router.default'
        arguments:
            $inner: '@Symfonicat\Routing\ApplicationRouter.inner'

    Symfonicat\Service\SubdomainService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Symfonicat\Service\FileUploadService:
        arguments:
            $publicDir: '%kernel.project_dir%/public'

    Symfonicat\Security\AdminUserProvider:
        arguments:
            $cache: '@cache.app'

    Symfonicat\Twig\EncoreEntryTagsExtension:
        arguments:
            $entryFilesTwigExtension: '@webpack_encore.twig_entry_files_extension'

    symfonicat.redis_connection:
        class: Predis\ClientInterface
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%env(resolve:REDIS_URL)%'
            - { class: 'Predis\Client' }

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            $redis: '@symfonicat.redis_connection'
            $options:
                prefix: 'symfonicat_session:'
                ttl: 86400

    Symfonicat\Command\RedisDebugCommand:
        arguments:
            $redisUrl: '%env(string:REDIS_URL)%'
