// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#include <php.h>
#include <Zend/zend_API.h>
#include <Zend/zend_hash.h>
#include <Zend/zend_types.h>
#include <stddef.h>

#include "brotli_precompress.h"
#include "brotli_precompress_arginfo.h"


PHP_MINIT_FUNCTION(brotli_precompress) {
    
    return SUCCESS;
}

zend_module_entry brotli_precompress_module_entry = {STANDARD_MODULE_HEADER,
                                         "brotli_precompress",
                                         ext_functions,             /* Functions */
                                         PHP_MINIT(brotli_precompress),  /* MINIT */
                                         NULL,                      /* MSHUTDOWN */
                                         NULL,                      /* RINIT */
                                         NULL,                      /* RSHUTDOWN */
                                         NULL,                      /* MINFO */
                                         "1.0.0",                   /* Version */
                                         STANDARD_MODULE_PROPERTIES};
