// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#include <php.h>
#include <Zend/zend_API.h>
#include <Zend/zend_hash.h>
#include <Zend/zend_types.h>
#include <stddef.h>

#include "reverse.h"
#include "reverse_arginfo.h"
#include "_cgo_export.h"


PHP_MINIT_FUNCTION(reverse) {
    
    return SUCCESS;
}

zend_module_entry reverse_module_entry = {STANDARD_MODULE_HEADER,
                                         "reverse",
                                         ext_functions,             /* Functions */
                                         PHP_MINIT(reverse),  /* MINIT */
                                         NULL,                      /* MSHUTDOWN */
                                         NULL,                      /* RINIT */
                                         NULL,                      /* RSHUTDOWN */
                                         NULL,                      /* MINFO */
                                         "1.0.0",                   /* Version */
                                         STANDARD_MODULE_PROPERTIES};
PHP_FUNCTION(symfonicat_reverse)
{
    zend_string *value = NULL;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(value)
    ZEND_PARSE_PARAMETERS_END();
    zend_string *result = go_symfonicat_reverse(value);
    if (result) {
        RETURN_STR(result);
    }

	RETURN_EMPTY_STRING();
}

