// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#ifndef _REVERSE_H
#define _REVERSE_H

#include <php.h>
#include <stdint.h>

extern zend_module_entry reverse_module_entry;



#endif
